import { defineCollection, z } from "astro:content";
import { glob } from "astro/loaders";

const ResourceCategorySchema = z.enum([
  "web-animations",
  "web-pages",
  "ui-components",
  "patterns",
  "components",
  "pages",
  "prompts",
  "architectures",
  "boilerplates",
  "remotion",
  "database-schemas",
  "ultra-high-definition-pages",
  "design-styles",
  "music",
  "3d-models",
  "3d-interactions",
  "plugins",
  "recommendations",
]);

const ResourceTypeSchema = z.enum([
  "animation",
  "page",
  "component",
  "pattern",
  "prompt",
  "skill",
  "mcp-server",
  "architecture",
  "boilerplate",
  "schema",
  "recommendation",
]);

const ResourceDifficultySchema = z.enum(["easy", "med", "hard"]);

const ResourceTargetSchema = z.enum([
  "html",
  "react",
  "react-native",
  "expo",
  "next",
  "vue",
  "svelte",
  "astro",
  "typescript",
  "python",
  "markdown",
  "yaml",
  "json",
  "sql",
  "mermaid",
  "dbml",
]);

const ResourceCollectionSchema = z.enum([
  "saas",
  "motion",
  "hero",
  "cards",
  "dashboard",
  "remotion",
  "effects",
  "mobile-nav",
  "charts",
  "restaurant",
  "hotel",
  "clinic",
  "gym",
  "salon",
  "realestate",
  "editorial",
  "comics",
  "music",
  "wiki",
  "patterns",
  "web3",
  "gamedev",
  "storybook",
  "travel",
  "portfolio",
  "ecommerce",
  "science",
  "museum",
  "cookbook",
  "agency",
  "d2c",
  "ai-product",
  "fintech",
  "elearning",
  "delivery",
  "streaming",
  "jobs",
  "events",
  "nonprofit",
  "creator",
  "airline",
  "cowork",
  "auto",
  "legal",
  "insurance",
  "construction",
  "vet",
  "photography",
  "dental",
  "wedding",
  "podcast",
  "dating",
  "coach",
  "interior",
  "video",
  "mobile",
  "modern-css",
  "webgl",
  "accessibility",
  "ai",
  "devtools",
  "diy",
  "design",
]);

const resources = defineCollection({
  loader: glob({
    pattern: "*/index.mdx",
    base: "../../packages/content/resources",
  }),
  schema: z.object({
    slug: z.string(),
    title: z.string(),
    description: z.string(),
    category: ResourceCategorySchema,
    type: ResourceTypeSchema,
    tags: z.array(z.string()).default([]),
    collections: z.array(ResourceCollectionSchema).default([]),
    tech: z.array(z.string()).default([]),
    difficulty: ResourceDifficultySchema,
    targets: z.array(ResourceTargetSchema).default([]),
    preview: z.string().optional(),
    labRoute: z.string().optional(),
    license: z.string().default("MIT"),
    author: z
      .object({
        name: z.string(),
        src: z.string(),
      })
      .optional(),
    createdAt: z
      .union([z.string(), z.date()])
      .transform((v) => (v instanceof Date ? v.toISOString().slice(0, 10) : v)),
    updatedAt: z
      .union([z.string(), z.date()])
      .transform((v) => (v instanceof Date ? v.toISOString().slice(0, 10) : v)),
  }),
});

export const collections = { resources };
