// Progressive enhancement only. The carousel's snapping and marker dots
// work with this whole file deleted. Here we add a live counter, a progress
// bar, prev/next buttons, and fallback-dot highlighting.
(function () {
  "use strict";

  const track = document.getElementById("track");
  const slides = Array.prototype.slice.call(track.querySelectorAll(".slide"));
  const total = slides.length;

  const currentEl = document.getElementById("current");
  const totalEl = document.getElementById("total");
  const progressBar = document.getElementById("progressBar");
  const progress = progressBar.parentElement;
  const fallbackDots = Array.prototype.slice.call(
    document.querySelectorAll(".fallback-dots a")
  );
  const supportHint = document.getElementById("supportHint");

  totalEl.textContent = String(total);

  // ---- Feature-detect native ::scroll-marker so we can tell the user ----
  const hasScrollMarker =
    typeof CSS !== "undefined" &&
    CSS.supports &&
    CSS.supports("selector(::scroll-marker)");

  supportHint.classList.toggle("is-native", hasScrollMarker);
  supportHint.textContent = hasScrollMarker
    ? "Native ::scroll-marker supported — the dots are generated by CSS."
    : "::scroll-marker not supported here — showing the anchor-link fallback dots.";

  // ---- Track the centered slide with IntersectionObserver ----
  let activeIndex = 0;

  function setActive(index) {
    if (index === activeIndex) return;
    activeIndex = index;

    currentEl.textContent = String(index + 1);
    progressBar.style.width = ((index + 1) / total) * 100 + "%";
    progress.setAttribute("aria-valuenow", String(index + 1));

    fallbackDots.forEach(function (dot, i) {
      dot.classList.toggle("is-active", i === index);
    });
  }

  const io = new IntersectionObserver(
    function (entries) {
      // The most-visible intersecting slide wins.
      let best = null;
      entries.forEach(function (entry) {
        if (
          entry.isIntersecting &&
          (!best || entry.intersectionRatio > best.intersectionRatio)
        ) {
          best = entry;
        }
      });
      if (best) {
        setActive(slides.indexOf(best.target));
      }
    },
    { root: track, threshold: [0.5, 0.75, 1] }
  );

  slides.forEach(function (slide) {
    io.observe(slide);
  });

  // ---- Prev / next buttons ----
  document.querySelectorAll(".btn[data-dir]").forEach(function (btn) {
    btn.addEventListener("click", function () {
      const dir = parseInt(btn.getAttribute("data-dir"), 10);
      const next = Math.min(total - 1, Math.max(0, activeIndex + dir));
      slides[next].scrollIntoView({
        behavior: matchMedia("(prefers-reduced-motion: reduce)").matches
          ? "auto"
          : "smooth",
        inline: "center",
        block: "nearest",
      });
    });
  });

  // ---- Arrow-key support when the track is focused ----
  track.addEventListener("keydown", function (e) {
    if (e.key !== "ArrowLeft" && e.key !== "ArrowRight") return;
    e.preventDefault();
    const dir = e.key === "ArrowRight" ? 1 : -1;
    const next = Math.min(total - 1, Math.max(0, activeIndex + dir));
    slides[next].scrollIntoView({
      behavior: "smooth",
      inline: "center",
      block: "nearest",
    });
  });

  // Initialise UI to the first slide.
  progressBar.style.width = 100 / total + "%";
})();
