export const RESOURCE_COLLECTION_IDS = [
  "saas",
  "motion",
  "hero",
  "cards",
  "dashboard",
  "remotion",
  "effects",
  "mobile-nav",
  "charts",
  "restaurant",
  "clinic",
  "gym",
  "salon",
  "realestate",
  "editorial",
  "comics",
  "music",
  "wiki",
  "patterns",
  "web3",
  "gamedev",
  "storybook",
  "travel",
  "portfolio",
  "ecommerce",
  "science",
  "cookbook",
  "museum",
  "agency",
  "d2c",
  "ai-product",
  "fintech",
  "elearning",
  "delivery",
  "streaming",
  "jobs",
  "events",
  "nonprofit",
  "creator",
  "hotel",
  "airline",
  "cowork",
  "auto",
  "legal",
  "insurance",
  "construction",
  "vet",
  "photography",
  "dental",
  "wedding",
  "podcast",
  "dating",
  "coach",
  "interior",
  "video",
  "mobile",
  "modern-css",
  "webgl",
] as const;

export type ResourceCollection = (typeof RESOURCE_COLLECTION_IDS)[number];
export type CollectionFilterValue = ResourceCollection | "all";

export const ALL_COLLECTION_FILTER_VALUE: CollectionFilterValue = "all";

/** Industry vertical collections — show a "New" badge in the library explorer. */
export const NEW_LIBRARY_COLLECTION_IDS = [
  "restaurant",
  "clinic",
  "gym",
  "salon",
  "realestate",
  "editorial",
  "comics",
  "music",
  "wiki",
  "patterns",
  "web3",
  "gamedev",
  "storybook",
  "travel",
  "portfolio",
  "ecommerce",
  "science",
  "cookbook",
  "museum",
  "agency",
  "d2c",
  "ai-product",
  "fintech",
  "elearning",
  "delivery",
  "streaming",
  "jobs",
  "events",
  "nonprofit",
  "creator",
  "hotel",
  "airline",
  "cowork",
  "auto",
  "legal",
  "insurance",
  "construction",
  "vet",
  "photography",
  "dental",
  "wedding",
  "podcast",
  "dating",
  "coach",
  "interior",
  "video",
] as const satisfies readonly ResourceCollection[];

const newLibraryCollectionIdsSet = new Set<ResourceCollection>(NEW_LIBRARY_COLLECTION_IDS);

export function isNewLibraryCollection(id: ResourceCollection): boolean {
  return newLibraryCollectionIdsSet.has(id);
}

export const IS_NEW_RECOMMENDATIONS_SECTION = true;

export interface LibraryCollection {
  id: ResourceCollection;
  titleKey: `collection.${ResourceCollection}.title`;
  descriptionKey: `collection.${ResourceCollection}.desc`;
  accentToken: string;
  order: number;
}

export const libraryCollections: LibraryCollection[] = [
  {
    id: "saas",
    titleKey: "collection.saas.title",
    descriptionKey: "collection.saas.desc",
    accentToken: "collection-saas",
    order: 1,
  },
  {
    id: "motion",
    titleKey: "collection.motion.title",
    descriptionKey: "collection.motion.desc",
    accentToken: "collection-motion",
    order: 2,
  },
  {
    id: "hero",
    titleKey: "collection.hero.title",
    descriptionKey: "collection.hero.desc",
    accentToken: "collection-hero",
    order: 3,
  },
  {
    id: "cards",
    titleKey: "collection.cards.title",
    descriptionKey: "collection.cards.desc",
    accentToken: "collection-cards",
    order: 4,
  },
  {
    id: "dashboard",
    titleKey: "collection.dashboard.title",
    descriptionKey: "collection.dashboard.desc",
    accentToken: "collection-dashboard",
    order: 5,
  },
  {
    id: "remotion",
    titleKey: "collection.remotion.title",
    descriptionKey: "collection.remotion.desc",
    accentToken: "collection-remotion",
    order: 6,
  },
  {
    id: "effects",
    titleKey: "collection.effects.title",
    descriptionKey: "collection.effects.desc",
    accentToken: "collection-effects",
    order: 7,
  },
  {
    id: "mobile-nav",
    titleKey: "collection.mobile-nav.title",
    descriptionKey: "collection.mobile-nav.desc",
    accentToken: "collection-mobile-nav",
    order: 8,
  },
  {
    id: "charts",
    titleKey: "collection.charts.title",
    descriptionKey: "collection.charts.desc",
    accentToken: "collection-charts",
    order: 9,
  },
  {
    id: "restaurant",
    titleKey: "collection.restaurant.title",
    descriptionKey: "collection.restaurant.desc",
    accentToken: "collection-restaurant",
    order: 10,
  },
  {
    id: "clinic",
    titleKey: "collection.clinic.title",
    descriptionKey: "collection.clinic.desc",
    accentToken: "collection-clinic",
    order: 11,
  },
  {
    id: "gym",
    titleKey: "collection.gym.title",
    descriptionKey: "collection.gym.desc",
    accentToken: "collection-gym",
    order: 12,
  },
  {
    id: "salon",
    titleKey: "collection.salon.title",
    descriptionKey: "collection.salon.desc",
    accentToken: "collection-salon",
    order: 13,
  },
  {
    id: "realestate",
    titleKey: "collection.realestate.title",
    descriptionKey: "collection.realestate.desc",
    accentToken: "collection-realestate",
    order: 14,
  },
  {
    id: "editorial",
    titleKey: "collection.editorial.title",
    descriptionKey: "collection.editorial.desc",
    accentToken: "collection-editorial",
    order: 15,
  },
  {
    id: "comics",
    titleKey: "collection.comics.title",
    descriptionKey: "collection.comics.desc",
    accentToken: "collection-comics",
    order: 16,
  },
  {
    id: "music",
    titleKey: "collection.music.title",
    descriptionKey: "collection.music.desc",
    accentToken: "collection-music",
    order: 17,
  },
  {
    id: "wiki",
    titleKey: "collection.wiki.title",
    descriptionKey: "collection.wiki.desc",
    accentToken: "collection-wiki",
    order: 18,
  },
  {
    id: "patterns",
    titleKey: "collection.patterns.title",
    descriptionKey: "collection.patterns.desc",
    accentToken: "collection-patterns",
    order: 19,
  },
  {
    id: "web3",
    titleKey: "collection.web3.title",
    descriptionKey: "collection.web3.desc",
    accentToken: "collection-web3",
    order: 20,
  },
  {
    id: "gamedev",
    titleKey: "collection.gamedev.title",
    descriptionKey: "collection.gamedev.desc",
    accentToken: "collection-gamedev",
    order: 21,
  },
  {
    id: "storybook",
    titleKey: "collection.storybook.title",
    descriptionKey: "collection.storybook.desc",
    accentToken: "collection-storybook",
    order: 22,
  },
  {
    id: "travel",
    titleKey: "collection.travel.title",
    descriptionKey: "collection.travel.desc",
    accentToken: "collection-travel",
    order: 23,
  },
  {
    id: "portfolio",
    titleKey: "collection.portfolio.title",
    descriptionKey: "collection.portfolio.desc",
    accentToken: "collection-portfolio",
    order: 24,
  },
  {
    id: "ecommerce",
    titleKey: "collection.ecommerce.title",
    descriptionKey: "collection.ecommerce.desc",
    accentToken: "collection-ecommerce",
    order: 25,
  },
  {
    id: "science",
    titleKey: "collection.science.title",
    descriptionKey: "collection.science.desc",
    accentToken: "collection-science",
    order: 26,
  },
  {
    id: "cookbook",
    titleKey: "collection.cookbook.title",
    descriptionKey: "collection.cookbook.desc",
    accentToken: "collection-cookbook",
    order: 27,
  },
  {
    id: "museum",
    titleKey: "collection.museum.title",
    descriptionKey: "collection.museum.desc",
    accentToken: "collection-museum",
    order: 28,
  },
  {
    id: "agency",
    titleKey: "collection.agency.title",
    descriptionKey: "collection.agency.desc",
    accentToken: "collection-agency",
    order: 29,
  },
  {
    id: "d2c",
    titleKey: "collection.d2c.title",
    descriptionKey: "collection.d2c.desc",
    accentToken: "collection-d2c",
    order: 30,
  },
  {
    id: "ai-product",
    titleKey: "collection.ai-product.title",
    descriptionKey: "collection.ai-product.desc",
    accentToken: "collection-ai-product",
    order: 31,
  },
  {
    id: "fintech",
    titleKey: "collection.fintech.title",
    descriptionKey: "collection.fintech.desc",
    accentToken: "collection-fintech",
    order: 32,
  },
  {
    id: "elearning",
    titleKey: "collection.elearning.title",
    descriptionKey: "collection.elearning.desc",
    accentToken: "collection-elearning",
    order: 33,
  },
  {
    id: "delivery",
    titleKey: "collection.delivery.title",
    descriptionKey: "collection.delivery.desc",
    accentToken: "collection-delivery",
    order: 34,
  },
  {
    id: "streaming",
    titleKey: "collection.streaming.title",
    descriptionKey: "collection.streaming.desc",
    accentToken: "collection-streaming",
    order: 35,
  },
  {
    id: "jobs",
    titleKey: "collection.jobs.title",
    descriptionKey: "collection.jobs.desc",
    accentToken: "collection-jobs",
    order: 36,
  },
  {
    id: "events",
    titleKey: "collection.events.title",
    descriptionKey: "collection.events.desc",
    accentToken: "collection-events",
    order: 37,
  },
  {
    id: "nonprofit",
    titleKey: "collection.nonprofit.title",
    descriptionKey: "collection.nonprofit.desc",
    accentToken: "collection-nonprofit",
    order: 38,
  },
  {
    id: "creator",
    titleKey: "collection.creator.title",
    descriptionKey: "collection.creator.desc",
    accentToken: "collection-creator",
    order: 39,
  },
  {
    id: "hotel",
    titleKey: "collection.hotel.title",
    descriptionKey: "collection.hotel.desc",
    accentToken: "collection-hotel",
    order: 40,
  },
  {
    id: "airline",
    titleKey: "collection.airline.title",
    descriptionKey: "collection.airline.desc",
    accentToken: "collection-airline",
    order: 41,
  },
  {
    id: "cowork",
    titleKey: "collection.cowork.title",
    descriptionKey: "collection.cowork.desc",
    accentToken: "collection-cowork",
    order: 42,
  },
  {
    id: "auto",
    titleKey: "collection.auto.title",
    descriptionKey: "collection.auto.desc",
    accentToken: "collection-auto",
    order: 43,
  },
  {
    id: "legal",
    titleKey: "collection.legal.title",
    descriptionKey: "collection.legal.desc",
    accentToken: "collection-legal",
    order: 44,
  },
  {
    id: "insurance",
    titleKey: "collection.insurance.title",
    descriptionKey: "collection.insurance.desc",
    accentToken: "collection-insurance",
    order: 45,
  },
  {
    id: "construction",
    titleKey: "collection.construction.title",
    descriptionKey: "collection.construction.desc",
    accentToken: "collection-construction",
    order: 46,
  },
  {
    id: "vet",
    titleKey: "collection.vet.title",
    descriptionKey: "collection.vet.desc",
    accentToken: "collection-vet",
    order: 47,
  },
  {
    id: "photography",
    titleKey: "collection.photography.title",
    descriptionKey: "collection.photography.desc",
    accentToken: "collection-photography",
    order: 48,
  },
  {
    id: "dental",
    titleKey: "collection.dental.title",
    descriptionKey: "collection.dental.desc",
    accentToken: "collection-dental",
    order: 49,
  },
  {
    id: "wedding",
    titleKey: "collection.wedding.title",
    descriptionKey: "collection.wedding.desc",
    accentToken: "collection-wedding",
    order: 50,
  },
  {
    id: "podcast",
    titleKey: "collection.podcast.title",
    descriptionKey: "collection.podcast.desc",
    accentToken: "collection-podcast",
    order: 51,
  },
  {
    id: "dating",
    titleKey: "collection.dating.title",
    descriptionKey: "collection.dating.desc",
    accentToken: "collection-dating",
    order: 52,
  },
  {
    id: "coach",
    titleKey: "collection.coach.title",
    descriptionKey: "collection.coach.desc",
    accentToken: "collection-coach",
    order: 53,
  },
  {
    id: "interior",
    titleKey: "collection.interior.title",
    descriptionKey: "collection.interior.desc",
    accentToken: "collection-interior",
    order: 54,
  },
  {
    id: "video",
    titleKey: "collection.video.title",
    descriptionKey: "collection.video.desc",
    accentToken: "collection-video",
    order: 55,
  },
  {
    id: "mobile",
    titleKey: "collection.mobile.title",
    descriptionKey: "collection.mobile.desc",
    accentToken: "collection-mobile",
    order: 56,
  },
  {
    id: "modern-css",
    titleKey: "collection.modern-css.title",
    descriptionKey: "collection.modern-css.desc",
    accentToken: "collection-modern-css",
    order: 57,
  },
  {
    id: "webgl",
    titleKey: "collection.webgl.title",
    descriptionKey: "collection.webgl.desc",
    accentToken: "collection-webgl",
    order: 58,
  },
];

export const libraryCollectionIdsSet = new Set<ResourceCollection>(RESOURCE_COLLECTION_IDS);

export function isResourceCollection(value: string): value is ResourceCollection {
  return libraryCollectionIdsSet.has(value as ResourceCollection);
}
