#!/usr/bin/env bun
/**
 * Supply-chain security verifier.
 *
 * Re-checks that every defense layer described in SUPPLY_CHAIN_SECURITY.md is
 * still wired and reports the current vulnerability / blocked-script state.
 * Writes a timestamped report to SECURITY_REPORT.md.
 *
 * Run before pulling new deps, before deploys, or routinely:
 *   bun run security:verify
 *
 * Exit code is 0 even when CVEs exist (transitive dev-dep advisories are
 * expected); it is non-zero only when a DEFENSE LAYER is missing/broken —
 * that is the signal that the repo is no longer hardened.
 */

import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (p) => {
  try {
    return readFileSync(join(root, p), "utf8");
  } catch {
    return "";
  }
};
const run = (cmd) => {
  try {
    return execSync(cmd, { cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
  } catch (e) {
    // bun audit exits non-zero when vulns exist; we still want its stdout.
    return `${e.stdout ?? ""}${e.stderr ?? ""}`;
  }
};

const checks = [];
const add = (name, ok, detail) => checks.push({ name, ok, detail });

// 1. bun >= 1.3 (older bun silently ignores the hardening keys)
const bunVer = run("bun --version").trim();
const [maj, min] = bunVer.split(".").map(Number);
add("bun >= 1.3", maj > 1 || (maj === 1 && min >= 3), `found ${bunVer || "unknown"}`);

// 2. Install cooldown configured
const bunfig = read("bunfig.toml");
const cooldownMatch = bunfig.match(/minimumReleaseAge\s*=\s*(\d+)/);
add(
  "Install cooldown (minimumReleaseAge)",
  Boolean(cooldownMatch),
  cooldownMatch ? `${cooldownMatch[1]}s (${(Number(cooldownMatch[1]) / 86400).toFixed(0)} days)` : "MISSING from bunfig.toml",
);

// 3. Socket scanner configured + installed
const scannerConfigured = /\[install\.security\][\s\S]*scanner\s*=\s*"@socketsecurity\/bun-security-scanner"/.test(bunfig);
const pkg = JSON.parse(read("package.json") || "{}");
const scannerInstalled = Boolean(pkg.devDependencies?.["@socketsecurity/bun-security-scanner"]);
add(
  "Socket pre-install scanner",
  scannerConfigured && scannerInstalled,
  `${scannerConfigured ? "configured" : "NOT configured"} / ${scannerInstalled ? "installed" : "NOT installed"}`,
);

// 4. No reckless blanket trust
const trusted = pkg.trustedDependencies ?? [];
add(
  "Postinstall scripts not blanket-trusted",
  !trusted.includes("*") && !trusted.includes("--all"),
  trusted.length ? `${trusted.length} explicitly trusted` : "none explicitly trusted (bun default allow-list only)",
);

// --- on-demand scans -------------------------------------------------------

const auditOut = run("bun audit");
const vulnLine = auditOut.match(/(\d+) vulnerabilities?.*$/m)?.[0] ?? "audit produced no summary line";
const vulnCount = Number(auditOut.match(/(\d+) vulnerabilities/)?.[1] ?? 0);

const untrustedOut = run("bun pm untrusted");
const blockedPkgs = [...untrustedOut.matchAll(/^\.\/node_modules\/(.+?)\s/gm)].map((m) => m[1]);

// --- verdict ---------------------------------------------------------------

const defensesOk = checks.every((c) => c.ok);
const ts = new Date().toISOString();

const md = `# Security report

> Generated by \`bun run security:verify\` (\`scripts/security-verify.mjs\`).
> Regenerate before pulling new dependencies, before a deploy, or routinely.
> See **SUPPLY_CHAIN_SECURITY.md** for what each layer does.

- **Generated:** ${ts}
- **Defense layers:** ${defensesOk ? "✅ ALL ACTIVE" : "❌ ONE OR MORE BROKEN — repo not hardened"}
- **Known CVEs in lockfile:** ${vulnCount} (transitive dev-dep advisories expected; not malware)
- **Blocked postinstall scripts:** ${blockedPkgs.length}

## Defense layers (must all pass)

| Layer | Status | Detail |
| --- | --- | --- |
${checks.map((c) => `| ${c.name} | ${c.ok ? "✅" : "❌"} | ${c.detail} |`).join("\n")}

## Known vulnerabilities (\`bun audit\`)

\`${vulnLine.trim()}\`

These are almost always **transitive** advisories inside dev tooling (astro, vite,
their glob/parse deps). Triage with \`/pkg-audit\`; fix with \`bun update\` once a
patched version clears the 3-day cooldown. CVEs here do **not** mean the repo is
compromised — the cooldown + Socket scanner are what guard against malicious
*new* releases.

## Blocked postinstall scripts (\`bun pm untrusted\`)

${
  blockedPkgs.length
    ? `bun blocked lifecycle scripts for:\n\n${blockedPkgs.map((p) => `- \`${p}\``).join("\n")}\n\nReview each. Trust ONE you recognize with \`bun pm trust <pkg>\`. **Never \`bun pm trust --all\`.**`
    : "None blocked this run."
}

---

_Re-run: \`bun run security:verify\`. Routine triage: \`/pkg-audit\`._
`;

writeFileSync(join(root, "SECURITY_REPORT.md"), md);

// Console summary
console.log(`\nSupply-chain verify @ ${ts}`);
for (const c of checks) console.log(`  ${c.ok ? "✅" : "❌"} ${c.name} — ${c.detail}`);
console.log(`  • ${vulnLine.trim()}`);
console.log(`  • ${blockedPkgs.length} blocked postinstall script(s)`);
console.log(`\nReport written to SECURITY_REPORT.md`);

if (!defensesOk) {
  console.error("\n❌ A defense layer is missing — repo is NOT hardened. See report.");
  process.exit(1);
}
console.log("\n✅ All defense layers active.");
