-- Prompt Designer bootstrap schema for Supabase.
-- Run this file in the Supabase SQL editor for the project used by `apps/prompt-designer`.
-- If you do not want Supabase yet, set `VITE_DATA_PROVIDER=local` in `apps/prompt-designer/.env`.
-- RLS is intentionally not enabled here so the browser app can work during local development.

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.authors (
  id bigint generated by default as identity primary key,
  name text not null,
  email text,
  team text,
  created_at timestamptz not null default timezone('utc', now()),
  constraint authors_name_key unique (name)
);

create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default timezone('utc', now()),
  constraint tags_name_key unique (name)
);

create table if not exists public.tools (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  configuration jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  constraint tools_name_key unique (name)
);

create table if not exists public.prompts (
  id bigint generated by default as identity primary key,
  author_id bigint not null references public.authors (id) on delete restrict,
  title text not null,
  description text,
  version text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.prompt_components (
  id bigint generated by default as identity primary key,
  prompt_id bigint not null references public.prompts (id) on delete cascade,
  component_key text not null,
  component_label text not null,
  content text not null default '',
  order_index integer not null default 0,
  is_enabled boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint prompt_components_prompt_id_component_key_key unique (prompt_id, component_key)
);

create table if not exists public.prompt_tags (
  prompt_id bigint not null references public.prompts (id) on delete cascade,
  tag_id bigint not null references public.tags (id) on delete cascade,
  primary key (prompt_id, tag_id)
);

create table if not exists public.prompt_tools (
  prompt_id bigint not null references public.prompts (id) on delete cascade,
  tool_id bigint not null references public.tools (id) on delete cascade,
  is_enabled boolean not null default true,
  primary key (prompt_id, tool_id)
);

create table if not exists public.prompt_variables (
  id bigint generated by default as identity primary key,
  prompt_id bigint references public.prompts (id) on delete cascade,
  variable_name text not null,
  variable_type text not null default 'text',
  description text,
  default_value text,
  is_required boolean not null default false,
  created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists prompt_variables_prompt_variable_name_idx
  on public.prompt_variables (prompt_id, variable_name)
  where prompt_id is not null;

create unique index if not exists prompt_variables_global_variable_name_idx
  on public.prompt_variables (variable_name)
  where prompt_id is null;

create table if not exists public.prompt_history (
  id bigint generated by default as identity primary key,
  prompt_id bigint not null references public.prompts (id) on delete cascade,
  previous_version_id bigint references public.prompts (id) on delete set null,
  change_type text not null,
  changed_by_id bigint references public.authors (id) on delete set null,
  change_message text,
  component_diffs jsonb,
  tags_added text[],
  tags_removed text[],
  tools_added text[],
  tools_removed text[],
  variables_added jsonb,
  variables_removed jsonb,
  variables_modified jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.information_sources (
  id bigint generated by default as identity primary key,
  author_id bigint not null references public.authors (id) on delete restrict,
  name text not null,
  description text,
  source_type text not null,
  content text,
  url text,
  metadata jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint information_sources_source_type_check
    check (source_type in ('link', 'json', 'secret', 'markdown', 'text', 'file'))
);

create index if not exists prompts_updated_at_idx on public.prompts (updated_at desc);
create index if not exists prompt_components_prompt_id_order_index_idx on public.prompt_components (prompt_id, order_index);
create index if not exists prompt_tags_prompt_id_idx on public.prompt_tags (prompt_id);
create index if not exists prompt_tools_prompt_id_idx on public.prompt_tools (prompt_id);
create index if not exists prompt_variables_prompt_id_idx on public.prompt_variables (prompt_id);
create index if not exists information_sources_created_at_idx on public.information_sources (created_at desc);

drop trigger if exists set_prompts_updated_at on public.prompts;
create trigger set_prompts_updated_at
before update on public.prompts
for each row
execute function public.set_updated_at();

drop trigger if exists set_prompt_components_updated_at on public.prompt_components;
create trigger set_prompt_components_updated_at
before update on public.prompt_components
for each row
execute function public.set_updated_at();

drop trigger if exists set_information_sources_updated_at on public.information_sources;
create trigger set_information_sources_updated_at
before update on public.information_sources
for each row
execute function public.set_updated_at();

create or replace function public.get_or_create_author(
  author_name text,
  author_email text default null,
  author_team text default null
)
returns bigint
language plpgsql
as $$
declare
  resolved_id bigint;
begin
  select id
  into resolved_id
  from public.authors
  where lower(name) = lower(trim(author_name))
  limit 1;

  if resolved_id is not null then
    update public.authors
    set email = coalesce(author_email, email),
        team = coalesce(author_team, team)
    where id = resolved_id;

    return resolved_id;
  end if;

  insert into public.authors (name, email, team)
  values (trim(author_name), nullif(trim(author_email), ''), nullif(trim(author_team), ''))
  returning id into resolved_id;

  return resolved_id;
end;
$$;

create or replace function public.get_or_create_tag(tag_name text)
returns bigint
language plpgsql
as $$
declare
  resolved_id bigint;
begin
  select id
  into resolved_id
  from public.tags
  where lower(name) = lower(trim(tag_name))
  limit 1;

  if resolved_id is not null then
    return resolved_id;
  end if;

  insert into public.tags (name)
  values (trim(tag_name))
  returning id into resolved_id;

  return resolved_id;
end;
$$;

create or replace function public.compose_prompt(p_prompt_id bigint)
returns text
language sql
stable
as $$
  select coalesce(
    string_agg(
      trim(both from concat(component_label, E'\n', content)),
      E'\n\n'
      order by order_index, id
    ),
    ''
  )
  from public.prompt_components
  where prompt_id = p_prompt_id
    and coalesce(is_enabled, true);
$$;

create or replace function public.calculate_prompt_diff(old_prompt_id bigint, new_prompt_id bigint)
returns jsonb
language sql
stable
as $$
  select jsonb_build_object(
    'old_prompt_id', old_prompt_id,
    'new_prompt_id', new_prompt_id,
    'before', public.compose_prompt(old_prompt_id),
    'after', public.compose_prompt(new_prompt_id)
  );
$$;

create or replace view public.prompts_with_components as
select
  p.id as prompt_id,
  p.title,
  p.description,
  p.version,
  p.created_at,
  p.updated_at,
  a.name as author_name,
  a.team as author_team,
  coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', pc.id,
        'component_key', pc.component_key,
        'component_label', pc.component_label,
        'content', pc.content,
        'order_index', pc.order_index,
        'is_enabled', pc.is_enabled,
        'created_at', pc.created_at,
        'updated_at', pc.updated_at
      )
      order by pc.order_index, pc.id
    ) filter (where pc.id is not null),
    '[]'::jsonb
  ) as components
from public.prompts p
left join public.authors a on a.id = p.author_id
left join public.prompt_components pc on pc.prompt_id = p.id
group by
  p.id,
  p.title,
  p.description,
  p.version,
  p.created_at,
  p.updated_at,
  a.name,
  a.team;

create or replace view public.latest_prompts_consolidated as
select
  p.id,
  p.title,
  p.description,
  p.version,
  p.created_at,
  p.updated_at,
  a.name as author_name,
  a.team as author_team,
  public.compose_prompt(p.id) as consolidated_prompt,
  tags.tags,
  tools.tools,
  vars.variable_count
from public.prompts p
left join public.authors a on a.id = p.author_id
left join lateral (
  select coalesce(array_agg(t.name order by t.name), '{}'::text[]) as tags
  from public.prompt_tags pt
  join public.tags t on t.id = pt.tag_id
  where pt.prompt_id = p.id
) tags on true
left join lateral (
  select coalesce(array_agg(tl.name order by tl.name), '{}'::text[]) as tools
  from public.prompt_tools ptl
  join public.tools tl on tl.id = ptl.tool_id
  where ptl.prompt_id = p.id
    and coalesce(ptl.is_enabled, true)
) tools on true
left join lateral (
  select count(*)::integer as variable_count
  from public.prompt_variables pv
  where pv.prompt_id = p.id
) vars on true
where coalesce(p.is_active, true);
